- name: Update package cache
  ansible.builtin.yum:
    update_cache: true

- name: Install git
  ansible.builtin.yum:
    name: git
    state: present

- name: Install python
  ansible.builtin.yum:
    name: python3
    state: present

- name: Install pip
  ansible.builtin.yum:
    name: python-pip
    state: present

- name: Install Docker
  ansible.builtin.yum:
    name: docker
    state: present

- name: Start docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Check docker service status
  ansible.builtin.command: systemctl status docker
  register: output

- debug: var=output
