---
- name: Clone Git Repository
  ansible.builtin.git:
    repo: 'https://github.com/Aquid16/CI-CD-Final'
    dest: /home/ec2-user/CI-CD-Final

- name: Build docker image
  community.docker.docker_image:
    name: FlaskApp
    api_version: 1.44
    source: local
    state: present

- name: Run the container
  ansible.builtin.docker_container:
    image: FlaskApp:latest
    name: Flask

- name: Check if container is running
  shell: docker ps
